### ISSUE TITLE
Setup GitHub actions

### ISSUE THREAD

**Issue by lilyxmeng** [jcal13/memory-model-editor#85]
Tasks:
- [ ] Create a file .github/workflows/test.yml with contents like:
  ```
  name: Run tests
  on:
      pull_request:
          types: [opened, synchronize, reopened, ready_for_review]
      push:
          branches:
              - main
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm run test
  ```
